### ISSUE TITLE
Write Dockerfile and Nomad example job file

### ISSUE THREAD

**Issue by jrasell** [elsevier-core-engineering/replicator#102]
**Description**

The 0.0.2 release brings new functionality which allows Replicator to be run as a Nomad job. We should therefore add an example job file and dockerfile with the image published to DockerHub.

**Comment by ericwestfall** [comment]
@jrasell mind if I grab this? It would be extremely useful to have this done before working on secrets integration with Vault since I'd like to leverage Nomad integration with Vault to deliver secrets to Replicator.
