### ISSUE TITLE
Protect Worker Pool Node Running The Replicator Leader From Termination During Cluster Scale-In

### ISSUE THREAD

**Issue by ericwestfall** [elsevier-core-engineering/replicator#119]
**Description**

With Replicator running as a Nomad job, it is now possible that we could initiate the termination of the worker pool node on which the Replicator leader is running during cluster scale in operations. 

To protect against this, the least-allocated node discovery method should be modified to filter out the worker pool node that is running the current Replicator leader. 

During initialization, if Replicator obtains leadership it should determine and store information about the worker pool node on which it is running and make this information available to the least-allocated node discovery method.

**Comment by jippi** [comment]
why? nomad should just reschedule replicator somewhere else? :p

**Comment by ericwestfall** [comment]
@jippi As the logic stands today, this would result in the worker node being moved into drain mode and left dangling as Replicator would be interrupted before the `TerminateInstances` API call was issued. 

So we either have to change the way in which nodes are drained, detached and terminated or we protect the node running the Replicator leader when choosing a worker node to terminate.

**Comment by jippi** [comment]
in my case, i would run replicator in a box that wasn't part of the ASG itself, like the box where nomad-servers run instead :) seem to be the most simple thing ?
