### ISSUE TITLE
AWS API Calls Are Forbidden When Replicator Is Running Within A Nomad Job

### ISSUE THREAD

**Issue by ericwestfall** [elsevier-core-engineering/replicator#128]
**Description**

The `client` package must make a number of AWS API calls to effect scaling operations. To authorize these API calls, Replicator assumes the presence of an IAM instance profile. 

When Replicator is running within the context of a Nomad job, it cannot obtain credentials from the host IAM instance profile. 

We need to add configuration parameters that allow credentials to be passed in and in ideal circumstances, these will be populated from Vault. 

**Steps to reproduce the issue:**
1. Run Replicator as a Nomad job
2. Trigger a scaling operation by introducing or removing load from the cluster. 
3. Within the Replicator logs, observe the scaling operations fail due to 403 responses from the AWS API.

**Describe the results you expected:**

Replicator should be able to perform all scaling operations and functions when running as a Nomad job.

**Describe the results you received:**

Replicator is unable to take any scaling actions or perform ancillary AWS API calls due to missing authentication information.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Replicator version:**
```
./replicator-local version
Replicator v0.0.2-dev
```

**Additional environment details:**

This is closely related to #82 which is in progress.

Example Nomad job file: 
```
job "replicator" {
  datacenters = ["opsshared"]
  region      = "us-east"
  type        = "service"

  update {
    stagger      = "10s"
    max_parallel = 1
  }

  group "replicator" {
    count = 1

    task "replicator" {
      driver = "exec"

      constraint {
        attribute = "${attr.kernel.name}"
        value     = "linux"
      }

      config {
        command = "replicator"
        args    = [
          "agent",
          "-aws-region=us-east-1",
          "-consul-token=<REDACTED>",
          "-cluster-autoscaling-group=container-agent-dev",
          "-log-level=DEBUG",
          "-cluster-max-size=3",
          "-cluster-min-size=1",
          "-cluster-scaling-enabled=true"
        ]
      }

      artifact {
        source = "https://s3.amazonaws.com/elsevier-tio-rap-opsshared-111045819866/replicator/dev/replicator"
      }

      resources {
        cpu    = 250
        memory = 60

        network {
          mbits = 5
        }
      }
    }
  }
}
```

**Debug log outputs from replicator:**

```
[DEBUG] core/cluster_scaling: scale in requests 0 has reached threshold 3
[DEBUG] client/nomad: Node ec22f0a7-0fb7-8b4f-e0d5-26a7be9c1833 will be excluded when calculating eligible worker pool nodes to be removed
[INFO] client/nomad: node ec2ae9a5-aa37-62fe-6dca-4c697eb0d691 has been placed in drain mode

[DEBUG] client/consul: the Consul session d5385afa-f947-cb67-a7e0-2880126b54ad has been renewed
[INFO] client/nomad: node ec2ae9a5-aa37-62fe-6dca-4c697eb0d691 has no active allocations
[INFO] core/runner: terminating AWS instance 10.169.23.122
[ERROR] core/runner: unable to successfully terminate AWS instance ec2ae9a5-aa37-62fe-6dca-4c697eb0d691: AccessDenied: User: arn:aws:sts::111045819866:assumed-role/container-agent-dev-us-east-1/i-0596863fe85b14189 is not authorized to perform: autoscaling:DetachInstances on resource: arn:aws:autoscaling:us-east-1:111045819866:autoScalingGroup:cb401494-f21b-493d-880d-1805f235ec54:autoScalingGroupName/container-agent-dev
	status code: 403, request id: 17991057-5485-11e7-9aca-1f93cfe7bd7a
[DEBUG] client/consul: the Consul session d5385afa-f947-cb67-a7e0-2880126b54ad has been renewed
```

**Comment by jippi** [comment]
I don't see this error, are you sure you got the right IAM policy? i took your job in the issue and ran it as-is against my nomad cluster, and all it has said for 5min is

```
[INFO] command/agent: running version 0.0.2-dev
[INFO] command/agent: starting replicator agent...
[INFO] client/consul: leadership lock successfully obtained at replicator/config/leader
```

**Comment by ericwestfall** [comment]
Right you are @jippi - after speaking with @jrasell our worker node IAM role did not have sufficient permissions. 

We will still address the issue of obtaining AWS IAM credentials via Vault in #82
