### ISSUE TITLE
Allow Node Discovery To Reference Consul Key/Value Store For Worker Pool Configuration

### ISSUE THREAD

**Issue by ericwestfall** [elsevier-core-engineering/replicator#204]
**Description**

Replicator should support retrieving worker pool configuration details from Consul rather than requiring all configuration details to reside in the client meta parameters. There are several reasons why users prefer not to maintain all configuration details in the meta parameters: 

- Worker pools that use immutable machine images with minimal runtime configuration performed during the cloud-init phase would require baking new images to implement or modify Replicator configuration parameters.

- Users without robust configuration management can find it cumbersome to modify client configuration across a large number of disparate worker pools and ensure the meta configuration parameters stay in sync within a worker pool.

This feature request proposes adding methods to the node discovery mechanism that will attempt to look in Consul for worker pool configuration. In this scenario, a user would need only specify a single meta configuration parameter: `replicator_worker_pool`. Replicator would use the Consul key root path, as defined in `-consul-key-root` and look down a standard path for a worker pool configuration JSON object. 

For example, if a client has `replicator_worker_pool` configured as `example-worker-pool` and no other Replicator configuration parameters are present, the node discovery mechanism would look for a configuration object in Consul at `replicator/config/nodes/example-worker-pool` and expect a JSON object similar to: 

```
{
  "replicator_cool_down": "300",
  "replicator_enabled": "true",
  "replicator_node_fault_tolerance": "1",
  "replicator_notification_uid": "REP2",
  "replicator_provider": "aws",
  "replication_region": "us-east-1",
  "replicator_retry_threshold": "3",
  "replicator_scaling_threshold": "3",
  "replicator_worker_pool": "example-worker-pool"
}

```

Thanks to @jippi for the feedback and talking through this feature request.

**Comment by jippi** [comment]
@ericwestfall excited for this feature, will allow us to use replicator, primary due to point 1 in the issue :)
