### ISSUE TITLE
Add Scaling Group Min/Max Threshold Autodiscovery In Cloud Scaling Provider

### ISSUE THREAD

**Issue by ericwestfall** [elsevier-core-engineering/replicator#205]
**Description**

At present, Replicator requires a user to specify the min/max values for a worker pool by setting `replicator_max_size` and `replicator_min_size`. Rather than requiring an explicit declaration, the scaling provider should simply detect the values declared on the scaling group.

**Comment by burdandrei** [comment]
will it be ok, if while starting replicator it'll take all nomad clients, receive their instance ID from meta, and then with describe instances will build a map of with nomad-client is running in what autoscaling group, after what will build the map of min/max instances per ASG?

**Comment by ericwestfall** [comment]
@burdandrei While it would be possible, the intention here is to do away with the concept of a separate min/max value in relation to cluster scaling for Replicator. The cloud provider model already implements a mechanism for cloud provider specific safety checks that must pass before a cluster scaling operation is permitted. The plan is to simply have the cloud provider check if a scaling operation would violate the min/max value associated with the underlying scaling group. 

I would prefer to keep the primary node discovery mechanism agnostic with respect to the cloud provider by relying only on the Nomad API and client meta configuration. With #204, we will permit you to store all meta configuration for a worker pool in Consul Key/Value which means you would need only a single meta configuration parameter in the client: `replicator_worker_pool`. 

Let me know if I'm missing something or you have a use case we're not considering!
