### ISSUE TITLE
Implement A Thread Limit For Concurrent Scaling Operations

### ISSUE THREAD

**Issue by jrasell** [elsevier-core-engineering/replicator#221]
**Description**

Job scaling can be particularly heavy on the cluster network due to the information required from Nomad to calculate scaling thresholds and figures. It would therefore be advisable to introduce a thread/worker limit queue for scaling runs. This would allow us to keep a sensible limit when running on large clusters.

**Comment by jippi** [comment]
or submit a PR for nomad to expose it in client stats - the data is there already :)

**Comment by ericwestfall** [comment]
@jippi that would definitely help reduce the number of API calls required and I've actually been looking at adding what we need for evaluation stats back into the Nomad API. However, reducing the API calls simply pushes the scaling issue out - there would still be some number of jobs/job groups/worker pools that would be able to overwhelm the Nomad API.

**Comment by jippi** [comment]
if replicator uses `allowStale` and point to localhost client, shouldn't that help with scaling out?

**Comment by ericwestfall** [comment]
By default, we already point to the `localhost` client @jippi, allowing `stale` for the API calls is a good idea and should be raised as a separate issue.

**Comment by ericwestfall** [comment]
**Design Proposal**

To address these concerns, we'll implement an upper-bound on concurrent scaling operations: 

1. The asynchronous job scaling method will implement a worker channel where scalable resources will be passed to a worker method to implement the scaling. We will implement a configurable limit to the number of simultaneous scaling operations permitted. 

1. The asynchronous job scaling method will implement a wait group to ensure all scalable resources are processed before returning to the runner and waiting for the next tick. This will ensure we respect the configured scaling interval and do not end up in a constant loop if the scaling actions take longer than the configured scaling interval. 

1. The asynchronous worker pool scaling method will be updated to implement point 1 to ensure consistency in behavior.

**Comment by ericwestfall** [comment]
Closed with #232
