### ISSUE TITLE
Replicator doesn't support Nomad ACL

### ISSUE THREAD

**Issue by xmackex** [elsevier-core-engineering/replicator#272]
**Description**

Replicator does not not support Nomad ACL

**Steps to reproduce the issue:**
1. Launch Nomad cluster with ACL enabled
2. Launch configured Replicator

**Describe the results you expected:**
403 errors on any job action

**Describe the results you received:**
Replicator should support Nomad ACLs

**Replicator version:**
Replicator v1.1.0-beta1

**Comment by ketzacoatl** [comment]
Has this issue been resolved, should it be closed?
