### ISSUE TITLE
Replicator should support mutex locking

### ISSUE THREAD

**Issue by jrasell** [elsevier-core-engineering/replicator#32]
Upon deciding whether scaling actions should be actioned, replicator should use a mutex lock to ensure that only one process has the ability to take action. This would allow replicator to run as a Nomad job, and is an all round better approach.

**Comment by jrasell** [comment]
@ericwestfall for this change I will need to move consul_key_location and consul_token out of the job scaling struct and into the top level as they will be used outside of JS. Do you think its worth opening a ticket to perform that work first, so that we can work on separate tickets without conflicts as we both need the updated location?

**Comment by ericwestfall** [comment]
Definitely - I was waiting to get the other PR merged so I could start work on state persistence so this is well timed.
