### ISSUE TITLE
Implement Cluster Scaling Threshold

### ISSUE THREAD

**Issue by ericwestfall** [elsevier-core-engineering/replicator#73]
**Description**

To ensure we do not react to fleeting changes in cluster utilization and capacity requirements, Replicator should evaluate utilization and cluster scaling constraints and require the cluster to violate these constraints a specified number of times before opting to take a scaling action. 

This could be implemented as a `-cluster-scaling-threshold` configuration flag and associated configuration file directive with a sensible default of `3`. 

Under this new behavior, if the cluster is determined to be under heavy CPU utilization, the cluster would need to violate the CPU constraint `3` consecutive times before Replicator would choose to take scaling action.

This is a significant design change and commentary is not only welcome but encouraged.

**Comment by jrasell** [comment]
Initial config thoughts:
- config parameter as described setup in the standard way
- within structs.State struct 'ClusterScalingRequests' or similarly named int type is created

Initial process thoughts:
- if a cluster scaling event is requested the 'ClusterScalingRequests' is incremented and checked against the threshold
- if the threshold is passed, the cluster will scale out
- if the threshold is not passed, replicator will skip and wait for another run
- if on the next round will still want to scale, point 1 and 2 is repeated
- if on the next round the cluster does not want to scale, we ensure 'ClusterScalingRequests' is set to 0 and continue
